{
 "title": "Reliability Review",
 "tags": [ "OverOps" ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environments",
    "label": "Env",
    "query": "environments({\"sorted\":\"true\"})"
   },
   {
    "name": "applications",
    "label": "Apps",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "servers",
    "label": "Server Groups",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "deployments",
    "label": "Deployments",
    "query": "deployments({\"environments\":\"$environments\", \"sorted\":true})"
   },
   { "name": "view", "label": "View", "query": "All Events" },
   {
    "name": "type",
    "label": "Type",
    "query": "eventTypes({\"environments\":\"$environments\", \"view\":\"$view\"})"
   },
   {
    "name": "pointsWanted",
    "label": "Points Wanted",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"points_wanted\", \"defaultValue\":24})"
   },
   {
    "name": "transactionPointsWanted",
    "label": "Points Wanted",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"transaction_points_wanted\", \"defaultValue\":100})"
   },
   {
    "name": "graphType",
    "label": "KPI",
    "query": "New Issues,Severe New Issues,Error Increases,Severe Error Increases,Slowdowns,Severe Slowdowns,Error Volume, Unique Errors,Error Rate"
   },
   { "name": "limit", "label": "Top", "query": "5,10" },
   {
    "name": "settingsPostfix",
    "query": "Weights are defined in the Settings dashboard"
   },
   { "name": "drilldownPostfix", "query": "Click to drill down" },
   { "name": "thresholds", "query": "70|85" },
   { "name": "postfixes", "query": "(R)|(Y)|(G)" },
   {
    "name": "limitApplications",
    "query": "limitVariable({\"values\":\"$applications\"})"
   },
   {
    "name": "limitDeployments",
    "query": "limitVariable({\"values\":\"$deployments\"})"
   },
   {
    "name": "limitServers",
    "query": "limitVariable({\"values\":\"$servers\"})"
   },
   {
    "name": "limitType",
    "query": "limitVariable({\"values\":\"$type\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments KPI: $graphType",
   "type": "grafana-piechart-panel",
   "description": "Chart the $graphType of the selected deployments. If no deployments are selected, the last $limit deployments are chosen. Scores are based on the weights set in the Settings dashboard. Deployments that are live are marked with an *.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "regressionReport({\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"view\":\"$view\",\"pointsWanted\":\"$pointsWanted\", \"transactionPointsWanted\":\"$transactionPointsWanted\",\"types\":\"$type\", \"render\":\"Graph\", \"mode\":\"Deployments\", \"limit\":\"$limit\", \"graphType\":\"$graphType\", \"sortType\":\"Descending\", \"postfixes\":\" $postfixes\", \"thresholds\":\"$thresholds\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apps KPI: $graphType",
   "type": "grafana-piechart-panel",
   "description": "Chart the $graphType of the key applications. Key applications are marked with * and appear first followed by live applications up to limit of  $limit applications in total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "regressionReport({\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"view\":\"$view\",\"pointsWanted\":\"$pointsWanted\", \"transactionPointsWanted\":\"$transactionPointsWanted\",\"types\":\"$type\", \"render\":\"Graph\", \"mode\":\"Applications\", \"limit\":\"$limit\", \"graphType\":\"$graphType\",\"postfixes\":\" $postfixes\", \"thresholds\":\"$thresholds\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Volume by Deployment",
   "type": "graph",
   "description": "Chart the error volume of the selected deployments. If no deployments are selected, the last $limit deployments are chosen. Deployments that are live are marked with an *.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "groupBy({\"type\":\"sum\",\"field\":\"deployment\",\"volumeType\":\"hits\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"types\":\"$type\",\"limit\":\"$limit\", \"pointsWanted\":\"$pointsWanted\", \"interval\":\"$__interval\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Volume by App",
   "type": "graph",
   "description": "Chart the $graphType of the key applications. Key applications are marked with * and appear first followed by live applications up to limit of  $limit applications in total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "groupBy({\"type\":\"sum\",\"field\":\"application\",\"volumeType\":\"hits\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"types\":\"$type\",\"limit\":\"$limit\", \"pointsWanted\":\"$pointsWanted\", \"interval\":\"$__interval\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}