{
 "title": "Application Reliability",
 "tags": [ "OverOps" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environments",
    "label": "Env",
    "query": "environments({\"sorted\":\"true\"})"
   },
   {
    "name": "applications",
    "label": "Apps",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "servers",
    "label": "Servers",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "deployments",
    "label": "Deployments",
    "query": "deployments({\"environments\":\"$environments\", \"sorted\":true})"
   },
   { "name": "view", "label": "View", "query": "All Events" },
   {
    "name": "type",
    "label": "Type",
    "query": "eventTypes({\"environments\":\"$environments\", \"view\":\"All Events\", \"types\":\"Logged Error|Uncaught Exception|Logged Warning|Swallowed Exception|HTTP Error|Timer|Caught Exception\"})"
   },
   {
    "name": "transactions",
    "label": "Transactions",
    "query": "transactions({\"environments\":\"$environments\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - 7d\",\"sorted\":\"true\"})"
   },
   {
    "name": "keyTransactions",
    "label": "Key Transactions",
    "query": "AppPeriodicPushTask|GracefulTask"
   },
   { "name": "pointsWanted", "label": "Points Wanted", "query": "24" },
   {
    "name": "deploymentName",
    "label": "DeploymentName",
    "query": "deploymentName({\"environments\":\"$environments\",\"deployments\":\"$deployments\",\"activeTimespan\":\"$activeTimespan\", \"baselineTimespan\":\"$baselineTimespan\", \"view\":\"All Events\"})"
   },
   { "name": "minBaselineTimespan", "label": "Min Baseline Timespan", "query": "20160" },
   { "name": "baselineTimespanFactor", "label": "Baseline Timespan Factor", "query": "4" },
   { "name": "minVolumeThreshold", "label": "Min Volume Threshold", "query": "50" },
   { "name": "minErrorRateThreshold", "label": "Min Error Rate Threshold", "query": "0.1" },
   { "name": "criticalRegressionDelta", "label": "Critical Regression Delta", "query": "1" },
   { "name": "regressionDelta", "label": "Regression Delta", "query": "0.5" },
   {
    "name": "criticalExceptionTypes",
    "label": "Critical Types",
    "query": "NullPointerException|IndexOutOfBoundsException|InvalidCastException|AssertionError"
   },
   {
    "name": "defaultTypes",
    "label": "Defaut Types",
    "query": "Logged Error|Logged Warning|HTTP Error|Timer"
   },
   {
    "name": "regressionName",
    "label": "regressionName",
    "query": "regressionName({\"environments\":\"$environments\",\"deployments\":\"$deployments\",\"activeTimespan\":0, \"minBaselineTimespan\":\"$minBaselineTimespan\",\"baselineTimespanFactor\":\"$baselineTimespanFactor\", \"view\":\"All Events\"})"
   },
   { "name": "active_timespan", "query": "1440" },
   { "name": "applySeasonality", "label": "applySeasonality", "query": "true,false" }
  ]
 },
 "panels": [
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"aggregate\":true,\"seriesName\":\"Throughput\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"avg_time\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"aggregate\":\"false\",\"transactions\":\"$transactions\",\"seriesName\":\"Avg Response (ms)\",\"pointsWanted\":\"$pointsWanted\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Key Transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"avg_time\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"aggregate\":\"true\",\"transactions\":\"$keyTransactions\",\"seriesName\":\"Avg Response (ms)\",\"pointsWanted\":\"$pointsWanted\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"aggregate\":true,\"seriesName\":\"Throughput\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "typesGraph({\"type\":\"sum\",\"graphType\":\"view\",\"volumeType\":\"hits\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"deployments\":\"$deployments\",\"servers\":\"$servers\",\"pointsWanted\":\"$pointsWanted\", \"types\":\"$type\", \"transactions\":\"$transactions\", \"defaultTypes\":\"$defaultTypes\"})\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$regressionName",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "regressions({\"fields\":\"link,type,issueType,message,error_location,entry_point,regression\", \"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"view\":\"$view\", \"activeTimespan\":\"$active_timespan\",\"minBaselineTimespan\":\"$minBaselineTimespan\",\"baselineTimespanFactor\":\"$baselineTimespanFactor\",\"minVolumeThreshold\":\"$minVolumeThreshold\",\"minErrorRateThreshold\":\"$minErrorRateThreshold\",\"regressionDelta\":\"$regressionDelta\",\"criticalRegressionDelta\":\"$criticalRegressionDelta\",\"applySeasonality\": \"$applySeasonality\",\"criticalExceptionTypes\":\"$criticalExceptionTypes\",\"maxColumnLength\":60, \"transactions\":\"$transactions\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New $type in last 5 deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "groupBy({\"type\":\"count\",\"field\":\"introduced_by\",\"limit\":5,\"volumeType\":\"hits\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"types\":\"$type\", \"pointsWanted\":24})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event By Tier",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"aggregate\":true,\"seriesName\":\"Throughput\",\"pointsWanted\":\"$pointsWanted\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "routingGraph({\"type\":\"sum\",\"graphType\":\"view\",\"volumeType\":\"hits\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"deployments\":\"$deployments\",\"servers\":\"$servers\",\"pointsWanted\":\"$pointsWanted\", \"types\":\"$type\", \"transactions\":\"$transactions\", \"defaultTypes\":\"$defaultTypes\",\"limit\":5})\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}