{
 "title": "Continuous Reliability",
 "tags": [ "OverOps" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeRange", "label": "Select a Time Range", "query": "4h,12h,24h,2d,7d,14d,30d" },
   {
    "name": "environments",
    "label": "Environments",
    "query": "environments({\"sorted\":\"true\"})"
   },
   {
    "name": "applications",
    "label": "Applications",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "servers",
    "label": "Servers",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   },
   {
    "name": "deployments",
    "label": "Deployments",
    "query": "deployments({\"environments\":\"$environments\",\"sorted\":\"true\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "New Errors: $deployments",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "volume({\"type\":\"count\",\"volumeType\":\"hits\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - $timeRange\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"introducedBy\":\"$deployments\",\"types\":\"Logged Error|Swallowed Exception|Logged Warning|Uncaught Exception|HTTP Error\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Volume: $deployments",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "volume({\"type\":\"sum\",\"volumeType\":\"hits\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - $timeRange\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"introducedBy\":\"$deployments\",\"types\":\"Logged Error|Swallowed Exception|Logged Warning|Uncaught Exception|HTTP Error\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last 5 Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "groupBy({\"type\":\"sum\",\"field\":\"introduced_by\",\"limit\":5,\"volumeType\":\"hits\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - $timeRange\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"types\":\"Logged Error|Swallowed Exception|Logged Warning|Uncaught Exception|HTTP Error\",\"interval\":\"$__interval\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last 7 Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "graph({\"type\":\"sum\",\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - 7d\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"pointsWanted\":7,\"seriesName\":\"Throughput\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "groupBy({\"type\":\"sum\",\"field\":\"type\",\"volumeType\":\"hits\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - 7d\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\",\"types\":\"Logged Error|Swallowed Exception|Logged Warning|Uncaught Exception|HTTP Error\",\"interval\":\"$__interval\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "events({\"fields\":\"link,type,message,error_location,entry_point,stats.hits,rate\",\"view\":\"All Events\",\"timeFilter\":\"time >= now() - $timeRange\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"introducedBy\":\"$deployments\",\"types\":\"Logged Error|Swallowed Exception|Logged Warning|Uncaught Exception|HTTP Error\",\"volumeType\":\"all\",\"maxColumnLength\":45})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}