{
 "title": "Logging Calculator",
 "tags": [ "OverOps" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environments",
    "label": "Env",
    "query": "environments({\"sorted\":true})"
   },
   {
    "name": "applications",
    "label": "Apps",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":true})"
   },
   {
    "name": "servers",
    "label": "Servers",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":true})"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "eventTypes({\"environments\":\"$environments\", \"view\":\"$view\"})"
   },
   {
    "name": "deployments",
    "label": "Deployments",
    "query": "deployments({\"environments\":\"$environments\", \"sorted\":true})"
   },
   {
    "name": "transactions",
    "label": "Transactions",
    "query": "transactions({\"environments\":\"$environments\",\"view\":\"$view\",\"timeFilter\":\"time >= now() - 7d\",\"sorted\":\"true\"})"
   },
   {
    "name": "pointsWanted",
    "label": "Points Wanted",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"points_wanted\", \"defaultValue\":24})"
   },
   { "name": "search", "label": "Find", "query": "<term>" },
   { "name": "splitLimit", "label": "Top %", "query": "5,10,25,33,50,66,75,90,100" },
   {
    "name": "costMatrix",
    "query": "{\"Caught Exception\":.00003,\"HTTP Error\":.00003,\"Logged Error\":.00003,\"Logged Warning\":.00003,\"Swallowed Exception\":.0000,\"Timer\":.0000,\"\":.0000}"
   },
   { "name": "view", "label": "View", "query": "All Events" },
   {
    "name": "apiHost",
    "query": "apiHost({\"type\":\"URL_NO_PORT\"})"
   },
   {
    "name": "apiPort",
    "query": "apiHost({\"type\":\"PORT\"})"
   },
   { "name": "graphType", "label": "Chart", "query": "BALANCE,AVG,SPOT" }
  ]
 },
 "panels": [
  {
   "title": "Stacked costs per exception(s)",
   "type": "graph",
   "description": "This graph shows the stacked details of  $splitLimit% exceptions cost. You can use: \n- SPOT to see the cost at a given time; \n- BALANCE to see the total cost up to the time; \n- AVG to see the average value of cost up to that time since start. \n\nYou can also select the exception(s) set you want to be displayed in the graph using the legend.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "costSplitGraph({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\", \"deployments\":\"$deployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"transactions\":\"$transactions\",\"limit\":\"$splitLimit\", \"searchText\":\"$search\",\"graphTrendType\":\"$graphType\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yearly Cost per Exception(Type+Location) ($)",
   "type": "grafana-piechart-panel",
   "description": "The biggest cost contributors (up to 6 different entries + a total reminder labelled \"CombinedSmallerItems\") for the period in exam.\n\nThe cost presented here are: \n- Yearly cost\n- Cost %\n\nPlease use the legend to enable/disable the desired slices set.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "graphCostPie({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\", \"deployments\":\"$deployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"transactions\":\"$transactions\",\"limit\":\"$splitLimit\", \"searchText\":\"$search\",\"graphTrendType\":\"$graphType\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Costs details per Exception",
   "type": "table",
   "description": "A list of all unique exceptions costs in the selected time frame and filter set with:\n- Cost % - the percentage of the overall cost\n- Cost - the actual cost over the all period\n- Yearly - the cost this exception will generate over 1 year time",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "costCalc({\"fields\":\"link,type,error_location,message,costpct,cost,costyrl\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\",\"maxColumnLength\":120,\"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\",\"searchText\":\"$search\",costData:{\"costHigherThan\":.0,\"costMatrix\":$costMatrix},\"tableLimit\":$splitLimit})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}