{
 "title": "Dashboard Diagnostics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queryCacheSize",
    "query": "queryDiagnostics({\"reportMode\":\"ApiCache\", \"outputMode\":\"SingleStat\"})"
   },
   {
    "name": "regressionCacheSize",
    "query": "queryDiagnostics({\"reportMode\":\"RegressionCache\", \"outputMode\":\"SingleStat\"})"
   },
   {
    "name": "logSize",
    "query": "queryDiagnostics({\"reportMode\":\"Log\", \"outputMode\":\"SingleStat\"})"
   },
   {
    "name": "threadsSize",
    "query": "queryDiagnostics({\"reportMode\":\"Thread\", \"outputMode\":\"SingleStat\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Query Cache: $queryCacheSize Items",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "queryDiagnostics({\"reportMode\":\"ApiCache\", \"reportMode\":\"Grid\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Regression Cache: $regressionCacheSize Items",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "queryDiagnostics({\"reportMode\":\"RegressionCache\", \"reportMode\":\"Grid\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages: $logSize Items",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "queryDiagnostics({\"reportMode\":\"Log\", \"outputMode\":\"Grid\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads Cache: $threadsSize Items",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "queryDiagnostics({\"reportMode\":\"Threads\", \"outputMode\":\"Grid\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}