{
 "title": "Event Diff",
 "tags": [ "OverOps" ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environments",
    "label": "Env",
    "query": "environments({\"sorted\":true})"
   },
   {
    "name": "applications",
    "label": "App A",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":true})"
   },
   {
    "name": "deployments",
    "label": "Dep A",
    "query": "deployments({\"environments\":\"$environments\", \"sorted\":true})"
   },
   {
    "name": "servers",
    "label": "Servers A",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":true})"
   },
   { "name": "transactions", "label": "Transactions", "query": "All" },
   {
    "name": "pointsWanted",
    "label": "Points Wanted",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"points_wanted\", \"defaultValue\":24})"
   },
   { "name": "splitLimit", "label": "Split Top", "query": "3,5,1" },
   { "name": "view", "label": "View", "query": "All Events" },
   {
    "name": "apiHost",
    "query": "apiHost({\"type\":\"URL_NO_PORT\"})"
   },
   {
    "name": "apiPort",
    "query": "apiHost({\"type\":\"PORT\"})"
   },
   {
    "name": "compareToApplications",
    "label": "App B",
    "query": "applications({\"environments\":\"$environments\",\"sorted\":true})"
   },
   {
    "name": "compareToDeployments",
    "label": "Dep B",
    "query": "deployments({\"environments\":\"$environments\", \"sorted\":true})"
   },
   {
    "name": "compareToServers",
    "label": "Servers B",
    "query": "servers({\"environments\":\"$environments\",\"sorted\":true})"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "eventTypes({\"environments\":\"$environments\", \"view\":\"$view\", \"timeFilter\":\"$timeFilter\"})"
   },
   { "name": "timeDiff", "label": "Time Diff", "query": "0m,1h,4h,8h,24h,2d,7d,14d,30d" },
   { "name": "search", "label": "Find", "query": "<term>" },
   {
    "name": "transactionFailureTypes",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"transaction_failures\", \"convertToArray\":\"true\", \"defaultValue\":\"Logged Error|Uncaught Exception|HTTP Error\"})"
   },
   {
    "name": "transactionPointsWanted",
    "query": "settingsVar({\"environments\":\"$environments\", \"name\":\"transaction_points_wanted\", \"defaultValue\":100})"
   },
   {
    "name": "newEventsDiffDesc",
    "query": "eventsDiffDesc({\"view\":\"$view\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\", \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\",\"timeDiff\":\"$timeDiff\"})"
   },
   {
    "name": "incEventsDiffDesc",
    "query": "eventsDiffDesc({\"view\":\"$view\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\", \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\",\"timeDiff\":\"$timeDiff\", \"diffType\":\"Increasing\"})"
   },
   {
    "name": "filterAEventsDiffDesc",
    "query": "eventsDiffDesc({\"view\":\"$view\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\", \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\",\"timeDiff\":\"$timeDiff\", \"descType\":\"FilterA\"})"
   },
   {
    "name": "filterBEventsDiffDesc",
    "query": "eventsDiffDesc({\"view\":\"$view\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\", \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\",\"timeDiff\":\"$timeDiff\", \"descType\":\"FilterB\"})"
   },
   { "name": "limit", "label": "Top", "query": "5,10,All" }
  ]
 },
 "panels": [
  {
   "title": "$type: $filterAEventsDiffDesc",
   "type": "graph",
   "description": "This graph shows the number of calls into transactions containing the selected events (Throughput). Overlaid on this are the top $splitLimit selected errors and the overall volume of all events (Times).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"deployments\":\"$deployments\",\"servers\":\"$servers\",\"aggregate\":true,\"seriesName\":\"Throughput\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "graph({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\", \"deployments\":\"$deployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"seriesName\":\"Volume\", \"transactions\":\"$transactions\", \"searchText\":\"$search\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "splitGraph({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$applications\", \"servers\":\"$servers\", \"deployments\":\"$deployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"transactions\":\"$transactions\", \"limit\":\"$splitLimit\", \"searchText\":\"$search\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$type:  $filterBEventsDiffDesc",
   "type": "graph",
   "description": "This graph shows the number of calls into transactions containing the selected events (Throughput). Overlaid on this are the top $splitLimit selected errors and the overall volume of all events (Times).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "transactionsGraph({\"graphType\":\"view\",\"volumeType\":\"invocations\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$compareToApplications\", \"deployments\":\"$compareToDeployments\",\"servers\":\"$compareToServers\",\"aggregate\":true,\"seriesName\":\"Throughput\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "graph({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$compareToApplications\", \"servers\":\"$compareToServers\", \"deployments\":\"$compareToDeployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"seriesName\":\"Volume\", \"transactions\":\"$transactions\", \"searchText\":\"$search\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "splitGraph({\"graphType\":\"view\",\"volumeType\":\"all\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\", \"applications\":\"$compareToApplications\", \"servers\":\"$compareToServers\", \"deployments\":\"$compareToDeployments\",\"pointsWanted\":\"$pointsWanted\",\"types\":\"$type\",\"transactions\":\"$transactions\", \"limit\":\"$splitLimit\", \"searchText\":\"$search\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$newEventsDiffDesc",
   "type": "table",
   "description": "A list of all unique errors in the selected time frame that only exist in the \"To\" App/Deployment/Server(s).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "eventsDiff({\"fields\":\"link,jira_issue_url,rate_desc,description,diff_desc,diff,type,message,stats.hits,rate,first_seen,introduced_by,jira_state\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\",\"maxColumnLength\":100, \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\", \"timeDiff\":\"$timeDiff\",\"diffTypes\":\"New\", \"limit\":\"$limit\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$incEventsDiffDesc",
   "type": "table",
   "description": "A list of all unique errors in the selected time frame that have increased in rate within the \"To\" App/Deployment/Server(s).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "eventsDiff({\"fields\":\"link,jira_issue_url,rate_desc,diff_desc,type,diff,description,message,stats.hits,rate,first_seen,jira_state\",\"view\":\"$view\",\"timeFilter\":\"$timeFilter\",\"environments\":\"$environments\",\"applications\":\"$applications\",\"servers\":\"$servers\",\"deployments\":\"$deployments\",\"volumeType\":\"all\",\"maxColumnLength\":100, \"types\":\"$type\",\"pointsWanted\":\"$pointsWanted\",\"transactions\":\"$transactions\", \"searchText\":\"$search\", \"compareToApplications\":\"$compareToApplications\", \"compareToDeployments\":\"$compareToDeployments\",\"compareToServers\":\"$compareToServers\", \"timeDiff\":\"$timeDiff\", \"diffTypes\":\"Increasing\", \"limit\":\"$limit\"})\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}